### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/reservations
Content-Type: application/json
###
POST http://localhost:8080/reservations
Content-Type: application/json

{
"courtName": "Court 2",
"date": "2026-03-28",
"timeSlot": "22:30"
}